### ISSUE TITLE
Reloading logic is defined in `uvicorn.run()`

### ISSUE THREAD

**Issue by peterschutt** [cofin/starlite-full-stack-example#3]
I had the `run-app` entrypoint in starlite-saqlalchemy configured  similar to this until I realised that calling `server.run()` sidesteps the reloading logic in uvicorn ([here](https://github.com/encode/uvicorn/blob/2351d5ff2b068d7bcba6eaccde83bc90b0727c89/uvicorn/main.py#L562-L569))

https://github.com/cofin/starlite-full-stack-example/blob/7259fc8711959b22b8faa5a676d3135458a7ae92/src/server/app/cli.py#L83-L84

So I moved back to calling `uvicorn.run()`([this commit](https://github.com/topsport-com-au/starlite-saqlalchemy/pull/231/commits/40e832be0dec58863669fc743d3c0d6ef73173db)).

**Comment by cofin** [comment]
Good to know this!   I'll make the updates.

**Comment by cofin** [comment]
I've updated this in the latest code.
