### ISSUE TITLE
Question about starting this repo.

### ISSUE THREAD

**Issue by nielsvanhooy** [cofin/starlite-full-stack-example#5]
Hi There,

i wanted to take a look at this repo and start the project locally.
however i am running into an issue. of which im not sure if im doing it correctly.

im trying to start the application with: uvicorn app.asgi:run_app --reload  
but that seems to be stuck on waiting for application startup.

INFO:     Will watch for changes in these directories: ['/home/donnyio/git/starlite-full-stack-example']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [81115] using WatchFiles
WARNING:  ASGI app factory detected. Using it, but please consider setting the --factory flag explicitly.
INFO:     Started server process [81117]
INFO:     Waiting for application startup. <-------------------

**Comment by cofin** [comment]
Hi, thanks for checking it out.  There is a CLI wrapped around `uvicorn` and `saq` that should help you launch the application.  `poetry run app run api` to launch the function you see [here](https://github.com/cofin/starlite-full-stack-example/blob/master/src/app/cli.py#L94).

You can access the CLI root with:
`poetry run app`

if you'd like to launch the app through the method you mention, you can try:
`uvicorn app.asgi:run_app --reload --factory`

Keep in mind, that you'll need to launch the background worker process separately when starting it this way.
